<a href="https://colab.research.google.com/github/ArthurMarqq/Projeto_Bootcamp01/blob/main/Analise_mortalidade_e_permanencia_SUS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importando o pandas para conseguir olhar os dados
import pandas as pd

In [9]:
# guardando os arquivos dentro de variaveis diferentes para facilitar as análises

dados_taxa_mortalidade = pd.read_csv('/content/A123627189_28_143_208.csv', encoding = "ISO-8859-1", sep=";", skiprows=3, skipfooter=12)
dados_media_permanencia = pd.read_csv('/content/A124453189_28_143_208.csv', encoding = "ISO-8859-1", sep=";", skiprows=3, skipfooter=12)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.

In [10]:
dados_taxa_mortalidade.head()

  Unidade da Federação 2008/Jan 2008/Fev  ... 2021/Ago 2021/Set Total
0          11 Rondônia      3,0      3,6  ...      4,7      5,6   4,4
1              12 Acre      3,5      4,5  ...      4,8      ...   4,8
2          13 Amazonas      4,6      4,7  ...      5,0      5,3   5,1
3           14 Roraima      4,5      4,6  ...      6,9      6,6   5,3
4              15 Pará      3,4      3,6  ...      4,3      3,8   3,9

[5 rows x 167 columns]